# Generated by Django 5.2.7 on 2025-10-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_empleado_estacion_servicio'),
        ('service_stations', '0004_alter_servicestation_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve y descriptivo del ticket.', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema o solicitud.')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('observaciones', models.TextField(blank=True, help_text='Notas de seguimiento, comentarios o resolución del ticket.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(help_text='Empleado que creó el ticket.', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to='employees.empleado')),
                ('estacion_servicio', models.ForeignKey(blank=True, help_text='Estación de servicio relacionada con el ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='service_stations.servicestation')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
