# Generated by Django 5.2.7 on 2025-10-13 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_empleado_estacion_servicio'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Comentario'), ('NOTA_INTERNA', 'Nota Interna')], default='COMENTARIO', max_length=20)),
                ('visibilidad', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PUBLICO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(help_text='Empleado que escribió el comentario.', on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='employees.empleado')),
                ('ticket', models.ForeignKey(help_text='Ticket al que pertenece este comentario.', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
        ),
    ]
