# Generated by Django 5.2.7 on 2025-10-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('COMENTARIO', 'Comentario'), ('ASIGNACION', 'Asignación'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('RESOLUCION', 'Resolución')], default='COMENTARIO', max_length=20),
        ),
    ]
