# Generated by Django 5.2.7 on 2025-10-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_comentario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_cerrado',
            field=models.DateTimeField(blank=True, help_text="Se actualiza automáticamente cuando el ticket se marca como 'Cerrado'.", null=True, verbose_name='Fecha de Cierre'),
        ),
    ]
