# Generated by Django 5.2.7 on 2026-05-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_vacacion_empleados_redireccion_and_more'),
        ('tickets', '0004_ticket_fecha_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Empleado específico del departamento que resolverá el problema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='employees.empleado', verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departamento_destino',
            field=models.ForeignKey(default=0, help_text='Área corporativa responsable de solucionar este ticket.', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_recibidos', to='employees.departamento', verbose_name='Departamento Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='folio',
            field=models.CharField(blank=True, help_text='Folio único generado automáticamente (Ej. TKT-00001).', max_length=20, null=True, unique=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En Proceso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10),
        ),
    ]
