# Generated by Django 5.2.7 on 2025-12-28 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('instruccion', models.TextField()),
                ('imagen', models.ImageField(upload_to='guias/pasos/')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='guides.guia')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
