# Generated by Django 5.2.7 on 2025-12-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guia',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='guia',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
