# Generated by Django 5.2.7 on 2026-01-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_guia_options_guia_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='sistema',
            field=models.CharField(choices=[('SLAM', 'SLAM'), ('SICA', 'SICA')], default='SLAM', max_length=4),
        ),
    ]
