# Generated by Django 5.2.7 on 2025-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_empleado_estacion_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título oficial del curso', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del curso', null=True)),
                ('fecha', models.DateField(blank=True, help_text='Fecha programada para el curso (YYYY-MM-DD)', null=True)),
                ('horario', models.TimeField(blank=True, help_text='Hora de inicio del curso (HH:MM)', null=True)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=1, help_text='Duración total del curso en horas (Ej. 2.5)', max_digits=4, null=True)),
                ('plataforma', models.CharField(blank=True, help_text='Plataforma o lugar (Ej. Zoom, Teams, Sala de Juntas 1)', max_length=100)),
                ('departamentos_destinados', models.ManyToManyField(blank=True, help_text='Departamentos que pueden ver y tomar este curso', related_name='cursos_disponibles', to='employees.departamento')),
                ('inscritos', models.ManyToManyField(blank=True, help_text='Empleados que están inscritos o han tomado este curso', related_name='cursos_inscritos', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['titulo'],
            },
        ),
    ]
