# Generated by Django 5.2.7 on 2025-10-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link',
            field=models.URLField(blank=True, help_text='Enlace a la sesión (Zoom, Teams) o a los materiales del curso', max_length=255, null=True),
        ),
    ]
