# Generated by Django 5.2.7 on 2025-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='es_general',
            field=models.BooleanField(default=False, help_text='Marcar si este curso es para TODOS los departamentos.', verbose_name='Curso General'),
        ),
    ]
