# Generated by Django 5.2.7 on 2025-10-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_empleado_user'),
        ('resources', '0004_curso_es_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial del formato o plantilla', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Propósito del formato y cuándo debe usarse.', null=True)),
                ('codigo_documento', models.CharField(blank=True, help_text='Código único de control (ej. RRHH-FOR-001)', max_length=50, null=True, unique=True)),
                ('palabras_clave', models.CharField(blank=True, help_text='Etiquetas separadas por comas para facilitar la búsqueda (ej. vacaciones, permiso, solicitud)', max_length=255)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('obsoleto', 'Obsoleto'), ('borrador', 'Borrador')], default='borrador', help_text='Estado del ciclo de vida del documento.', max_length=10)),
                ('archivo', models.FileField(blank=True, help_text='Subir el archivo (PDF, DOCX, XLSX, etc.)', null=True, upload_to='formatos/%Y/%m/')),
                ('enlace_externo', models.URLField(blank=True, help_text='Opcional: Si el formato está en Google Doc, SharePoint, etc.', max_length=255, null=True)),
                ('es_general', models.BooleanField(default=False, help_text='Marcar si este formato es para TODOS los departamentos.', verbose_name='Formato General')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('departamentos_destinados', models.ManyToManyField(blank=True, help_text="Departamentos que pueden ver y usar este formato (si no es 'general').", related_name='formatos_disponibles', to='employees.departamento')),
                ('tipo_documento', models.ForeignKey(help_text='Clasificación: Formato, Plantilla, Manual, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='formatos', to='resources.tipodocumento')),
            ],
            options={
                'verbose_name': 'Formato o Plantilla',
                'verbose_name_plural': 'Formatos y Plantillas',
                'ordering': ['nombre'],
            },
        ),
    ]
