# Generated by Django 5.2.7 on 2025-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_formato_descripcion_alter_formato_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de portada para el curso (Si se tiene)', null=True, upload_to='cursos_portadas/'),
        ),
        migrations.DeleteModel(
            name='Formato',
        ),
    ]
