# Generated by Django 5.2.7 on 2025-10-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_curso_imagen_delete_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('obsoleto', 'Obsoleto'), ('borrador', 'Borrador')], default='activo', help_text='Estado del ciclo de vida del documento.', max_length=10),
        ),
    ]
