# Generated by Django 5.2.7 on 2025-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_documento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', help_text='Define si el curso está activo o inactivo.', max_length=10, verbose_name='Estado'),
        ),
    ]
