# Generated by Django 5.2.7 on 2025-10-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_curso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('obsoleto', 'Obsoleto')], default='activo', help_text='Estado del ciclo de vida del documento.', max_length=10),
        ),
    ]
