# Generated by Django 5.2.7 on 2025-10-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_documento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(help_text='Fecha programada para el curso (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.TimeField(help_text='Hora de inicio del curso (HH:MM)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.URLField(help_text='Enlace a la sesión (Zoom, Teams) o a los materiales del curso', max_length=255),
        ),
    ]
