# Generated by Django 5.2.7 on 2025-10-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_curso_fecha_alter_curso_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='es_general',
            field=models.BooleanField(blank=True, default=False, help_text='Marcar si este curso es para TODOS los departamentos.', verbose_name='Curso General'),
        ),
    ]
