# Generated by Django 5.2.7 on 2025-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_curso_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='es_general',
            field=models.BooleanField(blank=True, default=False, help_text='Marcar si este curso es para TODOS los departamentos.', null=True, verbose_name='Curso General'),
        ),
    ]
