# Generated by Django 5.2.7 on 2025-10-30 16:31

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_alter_curso_es_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(help_text='Fecha programada para el curso (YYYY-MM-DD)'),
        ),
    ]
