# Generated by Django 5.2.7 on 2025-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_alter_curso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='es_general',
            field=models.BooleanField(default=False, help_text='Marcar si este curso es para TODOS los departamentos.', verbose_name='Curso General'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='plataforma',
            field=models.CharField(blank=True, help_text='Plataforma o lugar (Ej. Zoom, Teams, Sala de Juntas 1)', max_length=100),
        ),
    ]
