# Generated by Django 5.2.7 on 2025-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_alter_curso_es_general_alter_curso_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='plataforma',
            field=models.CharField(blank=True, help_text='Plataforma o lugar (Ej. Zoom, Teams, Sala de Juntas 1)', max_length=100, null=True),
        ),
    ]
