# Generated by Django 5.2.7 on 2025-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_alter_curso_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='es_general',
            field=models.BooleanField(help_text='Marcar si este curso es para TODOS los departamentos.', verbose_name='Curso General'),
        ),
    ]
