# Generated by Django 5.2.7 on 2025-10-31 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_alter_curso_es_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='es_general',
            field=models.BooleanField(default=True, help_text='Desmarcar si este curso NO es para TODOS los departamentos.', verbose_name='Curso General'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='es_general',
            field=models.BooleanField(default=True, help_text='Desmarcar si este formato NO es para TODOS los departamentos.', verbose_name='Formato General'),
        ),
        migrations.CreateModel(
            name='VideoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Video')),
                ('video_url', models.URLField(help_text='Pega el enlace normal de YouTube (watch?v=...) o Google Drive (file/d/.../view).', max_length=500, verbose_name='URL del Video')),
                ('ponente', models.CharField(blank=True, max_length=150, verbose_name='Ponente o Instructor')),
                ('fecha_grabacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Grabación')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_grabados', to='resources.curso', verbose_name='Curso al que pertenece')),
            ],
            options={
                'verbose_name': 'Video de Curso',
                'verbose_name_plural': 'Videoteca de Cursos',
                'ordering': ['-fecha_grabacion', 'titulo'],
            },
        ),
    ]
