# Generated by Django 5.2.7 on 2025-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_empleado_user'),
        ('resources', '0023_alter_curso_es_general_alter_documento_es_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurso',
            name='departamentos_destinados',
            field=models.ManyToManyField(blank=True, help_text="Departamentos que pueden ver este video (si no es 'general').", related_name='videos_disponibles', to='employees.departamento'),
        ),
    ]
