# Generated by Django 5.2.7 on 2025-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_videocurso_departamentos_destinados'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurso',
            name='es_general',
            field=models.BooleanField(default=True, help_text='Desmarcar si este formato NO es para TODOS los departamentos.', verbose_name='Formato General'),
        ),
    ]
