# Generated by Django 5.2.7 on 2025-11-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_videocurso_es_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('auto', 'Autoinscripción'), ('solicitud', 'Pedir inscribirse')], default='auto', help_text='Define si el usuario puede inscribirse directamente o debe solicitarlo.', max_length=10, verbose_name='Modalidad de Inscripción'),
        ),
    ]
