# Generated by Django 5.2.7 on 2025-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0026_curso_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del curso', null=True, verbose_name='Descripción'),
        ),
    ]
