# Generated by Django 5.2.7 on 2025-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duración total del curso en horas (Ej. 2.5)', max_digits=4, null=True, verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texto Alternativo (Alt)'),
        ),
    ]
