# Generated by Django 5.2.7 on 2025-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_alter_curso_duracion_horas_alter_slide_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='link',
            field=models.URLField(blank=True, help_text='Enlace a la sesión (Zoom, Teams) o a los materiales del curso', max_length=255, null=True),
        ),
    ]
