# Generated by Django 5.2.7 on 2025-11-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_empleado_estacion_servicio_and_more'),
        ('resources', '0029_alter_curso_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='INSCRITO', max_length=15, verbose_name='Estado de Participación')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Calificación (0-100)')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados_cursos/%Y/', verbose_name='Certificado/Diploma')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='resources.curso', verbose_name='Curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cursos', to='employees.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Inscripción y Historial',
                'verbose_name_plural': 'Inscripciones y Historial',
                'ordering': ['-fecha_finalizacion'],
                'unique_together': {('curso', 'empleado')},
            },
        ),
    ]
