# Generated by Django 5.2.7 on 2025-11-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_empleado_estacion_servicio_and_more'),
        ('resources', '0030_inscripcioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_historial_detallado', through='resources.InscripcionCurso', to='employees.empleado', verbose_name='Historial de Participación Detallado'),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_participantes', to='resources.curso', verbose_name='Curso'),
        ),
    ]
