# Generated by Django 5.2.7 on 2025-11-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_curso_participantes_alter_inscripcioncurso_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='estado',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DADO DE BAJA', 'Dado de Baja')], default='INSCRITO', max_length=15, verbose_name='Estado de Participación'),
        ),
    ]
