# Generated by Django 5.2.7 on 2025-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_alter_inscripcioncurso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('finalizado', 'Finalizado')], default='activo', help_text='Define si el curso está activo o inactivo.', max_length=10, verbose_name='Estado'),
        ),
    ]
