# Generated by Django 5.2.7 on 2025-11-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0033_alter_curso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación (0-100)'),
        ),
    ]
