# Generated by Django 5.2.7 on 2026-02-05 17:22

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0034_alter_inscripcioncurso_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='anio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='slide',
            name='mes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(storage=resources.models.OverwriteStorage(), upload_to=resources.models.slide_upload_path, verbose_name='Imagen'),
        ),
    ]
