# Generated by Django 5.2.7 on 2026-02-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_seccionpermiso'),
        ('resources', '0035_slide_anio_slide_mes_alter_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Procedimiento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('departamento', models.ForeignKey(blank=True, help_text='Opcional: Dejar vacío si el procedimiento aplica a varios departamentos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='employees.departamento')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='procedimiento',
            field=models.ForeignKey(blank=True, help_text='¿A qué flujo de trabajo pertenece? (Ej: Onboarding, Solicitud de Vacaciones)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='resources.procedimiento'),
        ),
    ]
