# Generated by Django 5.2.7 on 2026-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_seccionpermiso'),
        ('resources', '0036_procedimiento_documento_procedimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimiento',
            name='departamento',
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='departamento',
            field=models.ManyToManyField(blank=True, help_text='Opcional: Dejar vacío si el procedimiento aplica a varios departamentos.', related_name='procedimientos', to='employees.departamento'),
        ),
    ]
