# Generated by Django 5.2.7 on 2026-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0037_remove_procedimiento_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='categoria',
            field=models.CharField(choices=[('interno', 'Documentación Interna'), ('externo', 'Marco Normativo / Externo')], default='interno', max_length=20),
        ),
    ]
