# Generated by Django 5.2.7 on 2026-02-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0038_tipodocumento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurso',
            name='tematica',
            field=models.CharField(choices=[('aduanera', 'Formación Aduanera'), ('desarrollo', 'Desarrollo Humano'), ('otro', 'Otros temas')], default='aduanera', max_length=20, verbose_name='Temática del contenido'),
        ),
    ]
