# Generated by Django 5.2.7 on 2026-02-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0039_videocurso_tematica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TematicaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Temática')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Temática de Video',
                'verbose_name_plural': 'Temáticas de Videos',
            },
        ),
        migrations.RemoveField(
            model_name='videocurso',
            name='tematica',
        ),
        migrations.AddField(
            model_name='videocurso',
            name='tematica_vieja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
