# Generated by Django 5.2.7 on 2026-02-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0040_tematicavideo_remove_videocurso_tematica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocurso',
            name='tematica_vieja',
        ),
        migrations.AddField(
            model_name='videocurso',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='resources.tematicavideo', verbose_name='Temática'),
        ),
    ]
