# Generated by Django 5.2.7 on 2026-02-08 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0041_remove_videocurso_tematica_vieja_videocurso_tematica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segundo_actual', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('ultima_vista', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.videocurso')),
            ],
            options={
                'unique_together': {('usuario', 'video')},
            },
        ),
    ]
