# Generated by Django 5.2.7 on 2026-02-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0042_progresovideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgresoVideo',
        ),
    ]
