# Generated by Django 5.2.7 on 2026-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0043_delete_progresovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='sub_categoria',
            field=models.CharField(choices=[('procedimiento', 'Procedimiento / Manual'), ('formato', 'Formato / Plantilla'), ('otro', 'Otro')], default='formato', max_length=20, verbose_name='Subcategoría'),
        ),
    ]
