# Generated by Django 5.2.7 on 2026-03-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0044_tipodocumento_sub_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Procedimiento'),
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proceso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='resources.area')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['nombre'],
                'unique_together': {('area', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='resources.proceso'),
        ),
    ]
