# Generated by Django 5.2.7 on 2026-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_area_remove_procedimiento_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocurso',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
