# Generated by Django 5.2.7 on 2026-03-13 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0046_videocurso_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocurso',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro/Subida'),
        ),
    ]
