# Generated by Django 5.2.7 on 2026-03-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0047_alter_videocurso_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocurso',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Video de Curso', 'verbose_name_plural': 'Videoteca de Cursos'},
        ),
    ]
