# Generated by Django 5.2.7 on 2026-08-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_alter_videocurso_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proceso',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
