# Generated by Django 5.2.7 on 2025-10-13 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la estación de servicio.', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada o notas adicionales sobre la estación.')),
                ('ubicacion', models.CharField(blank=True, help_text="Dirección física o descripción de la ubicación (ej: 'Edificio B, Piso 3').", max_length=255)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto de la estación.', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('MANTENIMIENTO', 'En Mantenimiento'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=15)),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario responsable o gerente de la estación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estaciones_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estación de Servicio',
                'verbose_name_plural': 'Estaciones de Servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
