# Generated by Django 5.2.7 on 2025-10-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='responsable',
            field=models.CharField(blank=True, default='', help_text='Nombre del gerente o persona responsable de la estación.', max_length=255),
            preserve_default=False,
        ),
    ]
