# Generated by Django 5.2.7 on 2025-10-13 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_stations', '0002_alter_servicestation_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable o gerente de la estación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estaciones_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
    ]
