# Generated by Django 5.2.7 on 2025-10-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('service_stations', '0003_alter_servicestation_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Empleado responsable o gerente de la estación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estaciones_a_cargo', to='employees.empleado'),
        ),
    ]
