# Generated by Django 5.2.7 on 2025-10-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre corto de la política o permiso (ej: Política de correo electrónico)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de lo que permite este permiso.')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del empleado.', max_length=255)),
                ('email', models.EmailField(help_text='Correo electrónico del empleado.', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('posicion', models.CharField(blank=True, help_text='Ej: Coordinadora de RRHH', max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('password', models.CharField(help_text='Contraseña para sistemas externos (no para el admin de Django).', max_length=128)),
                ('firma_digital', models.ImageField(blank=True, help_text='Sube una imagen de la firma digital del empleado.', null=True, upload_to='firmas_empleados/')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.departamento')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Tipo de usuario al que pertenece el empleado. El administrador define sus permisos.', related_name='empleados', to='auth.group', verbose_name='Tipos de Usuario')),
                ('politicas_permisos', models.ManyToManyField(blank=True, help_text='Permisos específicos asignados directamente a este empleado.', related_name='empleados_con_permiso', to='employees.permiso', verbose_name='Políticas y Permisos Individuales')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
