# Generated by Django 5.2.7 on 2025-10-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('service_stations', '0004_alter_servicestation_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estacion_servicio',
            field=models.ForeignKey(blank=True, help_text='Estación de servicio a la que está asignado el empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='service_stations.servicestation'),
        ),
    ]
