# Generated by Django 5.2.7 on 2025-10-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_empleado_estacion_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
    ]
