# Generated by Django 5.2.7 on 2025-11-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_empleado_user'),
        ('service_stations', '0004_alter_servicestation_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estacion_servicio',
            field=models.ForeignKey(blank=True, help_text='Estación de servicio a la que está asignado el empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='service_stations.servicestation', verbose_name='Estación de Servicio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del empleado.', max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='posicion',
            field=models.CharField(blank=True, help_text='Ej: Coordinadora de RRHH', max_length=100, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
