# Generated by Django 5.2.7 on 2025-11-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_empleado_estacion_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha de finalización de labores (si aplica).', null=True, verbose_name='Fecha de Finalización/Baja'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha en la que el empleado inició labores. Crucial para antigüedad.', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento para cálculos de edad y beneficios.', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'Prefiero no especificar')], default='N', help_text='Sexo del empleado.', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.CharField(blank=True, help_text='Número de contacto en caso de emergencia.', max_length=20, verbose_name='Teléfono de Emergencia'),
        ),
    ]
