# Generated by Django 5.2.7 on 2025-12-04 21:22

import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0006_empleado_fecha_finalizacion_empleado_fecha_ingreso_and_more'),
        ('service_stations', '0004_alter_servicestation_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='politicas_permisos',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estacion_servicio',
            field=models.ForeignKey(blank=True, help_text='Centro de trabajo a la que está asignado el empleado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='service_stations.servicestation', verbose_name='Centro de Trabajo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grupos',
            field=models.ManyToManyField(blank=True, help_text='Tipo de usuario al que pertenece el empleado. El administrador define sus permisos.', related_name='empleados', to='auth.group', verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='posicion',
            field=models.CharField(blank=True, help_text='Ej: Coordinadora de RRHH', max_length=100, verbose_name='Puesto de Trabajo'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('firmado', models.BooleanField(default=False, help_text='Marcar si el expediente ya cuenta con las firmas necesarias.')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=employees.models.expediente_directory_path)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_firma', models.DateTimeField(blank=True, help_text='Fecha y hora en que se realizó la firma.', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='pendiente', max_length=20)),
                ('empleado', models.ForeignKey(help_text='Empleado al que pertenece este expediente o documento.', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='employees.empleado')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario al que pertenece este expediente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
    ]
