# Generated by Django 5.2.7 on 2025-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_empleado_politicas_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha en la que expira este documento (ej. fin de contrato).', null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('identificacion', 'Identificación'), ('certificacion', 'Certificación'), ('baja', 'Documento de Baja'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
