# Generated by Django 5.2.7 on 2025-12-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_expediente_fecha_vencimiento_expediente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='expediente',
            name='titulo_personalizado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_requerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.tipodocumentorequerido'),
        ),
    ]
