# Generated by Django 5.2.7 on 2025-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_tipodocumentorequerido_remove_expediente_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='tipo_requerido',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='titulo_personalizado',
        ),
        migrations.AddField(
            model_name='expediente',
            name='titulo',
            field=models.CharField(default='Documento', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TipoDocumentoRequerido',
        ),
    ]
