# Generated by Django 5.2.7 on 2025-12-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_expediente_tipo_requerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='requiere_firma',
            field=models.BooleanField(default=False, help_text='Indica si este documento necesita ser firmado digitalmente por el empleado.', verbose_name='¿Requiere firma?'),
        ),
    ]
