# Generated by Django 5.2.7 on 2025-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_expediente_requiere_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='categoria',
            field=models.CharField(choices=[('personal', 'Documentación Personal'), ('laboral', 'Documentación Laboral')], default='personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('identificacion', 'Identificación'), ('certificacion', 'Certificación'), ('comprobante', 'Comprobante'), ('constancia', 'Constancia'), ('documento', 'Documento'), ('acta', 'Acta'), ('baja', 'Documento de Baja'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
