# Generated by Django 5.2.7 on 2025-12-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_expediente_categoria_alter_expediente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('identificacion', 'Identificación'), ('certificacion', 'Certificación'), ('comprobante', 'Comprobante'), ('constancia', 'Constancia'), ('documento', 'Documento'), ('convenio', 'Convenio'), ('responsiva', 'Responsiva'), ('acta', 'Acta'), ('baja', 'Documento de Baja'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
