# Generated by Django 5.2.7 on 2025-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_expediente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='extension_plantilla',
            field=models.CharField(default='pdf', help_text='Extensión del archivo en static (pdf, docx, xlsx)', max_length=5),
        ),
    ]
