# Generated by Django 5.2.7 on 2025-12-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_expediente_extension_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='responsables',
            field=models.ManyToManyField(blank=True, help_text='Personas encargadas de dar seguimiento a este expediente.', related_name='expedientes_responsable', to='employees.empleado', verbose_name='Responsables'),
        ),
    ]
