# Generated by Django 5.2.7 on 2025-12-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_expediente_responsables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='employees.empleado', verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Tarea / Asunto',
                'verbose_name_plural': 'Tareas / Asuntos',
                'ordering': ['estado', 'fecha_vencimiento'],
            },
        ),
    ]
