# Generated by Django 5.2.7 on 2025-12-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de la tarea'),
        ),
    ]
