# Generated by Django 5.2.7 on 2025-12-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_tarea_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se completó'),
        ),
    ]
