# Generated by Django 5.2.7 on 2026-01-07 22:46

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_tarea_fecha_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('archivo_vacaciones', models.FileField(blank=True, null=True, upload_to=employees.models.vacaciones_directory_path, verbose_name='Formato de Vacaciones (PDF)')),
                ('archivo_roles', models.FileField(blank=True, null=True, upload_to=employees.models.vacaciones_directory_path, verbose_name='Formato de Roles y Pendientes')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DISFRUTADO', 'Disfrutado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la ausencia.')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_autorizadas', to='employees.empleado', verbose_name='Persona que autorizó')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='employees.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
