# Generated by Django 5.2.7 on 2026-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='permisos_secciones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de secciones a las que el empleado tiene acceso.', verbose_name='Permisos de Secciones'),
        ),
    ]
