# Generated by Django 5.2.7 on 2026-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_empleado_permisos_secciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre técnico sin espacios', max_length=100, unique=True)),
                ('etiqueta', models.CharField(help_text='Nombre que verá el Administrador (Ej: Ver Vacaciones)', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración de Sección',
                'verbose_name_plural': 'Configuraciones de Secciones',
            },
        ),
    ]
