# Generated by Django 5.2.7 on 2026-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_seccionpermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, help_text='Sube la foto del rostro del empleado para su identificación.', null=True, upload_to='fotos_empleados/', verbose_name='Foto de Perfil'),
        ),
    ]
