# Generated by Django 5.2.7 on 2026-03-02 21:20

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_empleado_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Primer día de la incapacidad según el documento', verbose_name='Fecha de Inicio')),
                ('duracion_dias', models.PositiveIntegerField(help_text='Cantidad de días autorizados', verbose_name='Días de duración')),
                ('archivo', models.FileField(help_text='Copia digital de la incapacidad', upload_to=employees.models.incapacidad_directory_path, verbose_name='Documento del IMSS')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incapacidades', to='employees.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'verbose_name_plural': 'Incapacidades',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
