# Generated by Django 5.2.7 on 2026-03-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_incapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
