# Generated by Django 5.2.7 on 2026-03-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_departamento_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='apodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
