# Generated by Django 5.2.7 on 2026-04-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_empleado_apodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='jefe',
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefe',
            field=models.ManyToManyField(blank=True, related_name='departamentos_bajo_mando', to='employees.empleado', verbose_name='Jefe de Departamento'),
        ),
    ]
