# Generated by Django 5.2.7 on 2026-04-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_remove_departamento_jefe_departamento_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='gerente_autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_autorizadas_gerencia', to='employees.empleado', verbose_name='Gerente que autorizó'),
        ),
    ]
