# Generated by Django 5.2.7 on 2026-04-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_vacacion_gerente_autorizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='autorizador_fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='autorizador_firmado',
            field=models.BooleanField(default=False, verbose_name='Jefe firmó'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='gerente_fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='gerente_firmado',
            field=models.BooleanField(default=False, verbose_name='Gerente firmó'),
        ),
        migrations.AlterField(
            model_name='vacacion',
            name='autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_autorizadas', to='employees.empleado', verbose_name='Jefe de Departamento que autorizó'),
        ),
    ]
