# Generated by Django 5.2.7 on 2026-04-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_vacacion_autorizador_fecha_firma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerente_general', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='es_gerente_general', to='employees.empleado', verbose_name='Gerente General')),
            ],
            options={
                'verbose_name': 'Configuración de RH',
                'verbose_name_plural': 'Configuración de RH',
            },
        ),
    ]
