# Generated by Django 5.2.7 on 2026-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_configuracionrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto relacionado'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_objeto',
            field=models.CharField(blank=True, help_text='Ej: vacacion, incapacidad, expediente', max_length=50, null=True),
        ),
    ]
