# Generated by Django 5.2.7 on 2026-04-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_tarea_objeto_id_tarea_tipo_objeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='dias_seleccionados',
            field=models.JSONField(blank=True, null=True, verbose_name='Días específicos'),
        ),
    ]
