# Generated by Django 5.2.7 on 2026-04-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_vacacion_dias_seleccionados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacacion',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Vacación', 'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.RemoveField(
            model_name='vacacion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='vacacion',
            name='fecha_inicio',
        ),
    ]
