# Generated by Django 5.2.7 on 2026-04-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_alter_vacacion_options_remove_vacacion_fecha_fin_and_more'),
    ]

    operations = [
    ]
