# Generated by Django 5.2.7 on 2026-04-27 17:31

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_auto_20260427_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=employees.models.MyStorage(), upload_to=employees.models.expediente_directory_path),
        ),
    ]
