# Generated by Django 5.2.7 on 2026-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_alter_expediente_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='empleados_redireccion',
            field=models.ManyToManyField(blank=True, related_name='redirecciones_asignadas', to='employees.empleado', verbose_name='Empleados asignados para redirección'),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='requiere_redireccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='requiere_respuesta_automatica',
            field=models.BooleanField(default=False, verbose_name='¿Requiere respuesta automática?'),
        ),
    ]
