# Generated by Django 5.2.7 on 2026-05-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_vacacion_empleados_redireccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(blank=True, help_text='Número o clave única de identificación del empleado (Ej. 001234 o EMP-001).', max_length=20, null=True, unique=True, verbose_name='Número de Empleado / ID'),
        ),
    ]
