# Generated by Django 5.2.7 on 2026-06-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_empleado_numero_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default='2000-01-01', help_text='Fecha en la que el empleado inició labores. Crucial para antigüedad.', verbose_name='Fecha de Ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01', help_text='Fecha de nacimiento para cálculos de edad y beneficios.', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='posicion',
            field=models.CharField(help_text='Ej: Coordinadora de RRHH', max_length=100, verbose_name='Puesto de Trabajo'),
        ),
    ]
