# Generated by Django 5.2.7 on 2025-10-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0001_initial'),
        ('service_stations', '0003_alter_servicestation_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estacion_servicio',
            field=models.ForeignKey(blank=True, help_text='Estación de servicio a la que pertenece el equipo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='service_stations.servicestation'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Empleado al que está asignado el equipo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='employees.empleado'),
        ),
    ]
