# Generated by Django 5.2.7 on 2025-10-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipo_estacion_servicio_alter_equipo_asignado_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie único del equipo', max_length=100, null=True, unique=True),
        ),
    ]
