# Generated by Django 5.2.7 on 2025-10-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipo_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado_registro',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
    ]
