# Generated by Django 5.2.7 on 2026-06-09 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_alter_empleado_fecha_ingreso_and_more'),
        ('equipment', '0004_equipo_estado_registro'),
        ('service_stations', '0004_alter_servicestation_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoequipo',
            options={'verbose_name': 'Estado Físico', 'verbose_name_plural': 'Estados Físicos'},
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='estado',
            new_name='estado_fisico',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='asignado_a',
        ),
        migrations.AddField(
            model_name='equipo',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisición', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estatus',
            field=models.CharField(choices=[('BODEGA', 'En Bodega'), ('ASIGNADO', 'Asignado'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Baja / Desechado'), ('PERDIDO', 'Robado / Extraviado')], default='BODEGA', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del equipo o herramienta', null=True, upload_to='equipos/fotos/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Detalles sobre raspones, fallas o particularidades.'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tipoequipo',
            name='categoria_general',
            field=models.CharField(blank=True, help_text='Ej. Tecnología, Seguridad, Vehículos, Ropa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estacion_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_fijos', to='service_stations.servicestation'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del equipo', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estadoequipo',
            name='nombre',
            field=models.CharField(help_text='Condición física: Ej. Nuevo, Bueno, Regular, Dañado', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, help_text='Se llena cuando el empleado devuelve el equipo', null=True)),
                ('archivo_responsiva', models.FileField(blank=True, null=True, upload_to='equipos/responsivas/')),
                ('notas_entrega', models.TextField(blank=True, help_text='Ej. Se entrega con cargador y funda.')),
                ('notas_devolucion', models.TextField(blank=True, help_text='Ej. Pantalla estrellada al devolver.')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='employees.empleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Historial de Asignaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
